[project]
name = "testing-of-software"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Denis Lylov", email = "denislylov2004@mail.ru" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
testing-of-software = "testing_of_software:main"

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
