[project]
name = "testing-of-software"
version = "0.1.0"
description = "Add your description here"
authors = [
    { name = "Denis Lylov", email = "denislylov2004@mail.ru" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
testing-of-software = "testing_of_software:main"

[tool.uv]
package = false

[tool.pytest.ini_options]
pythonpath = ["."]

[dependency-groups]
dev = [
    "pytest>=9.1.1",
    "pytest-cov>=7.1.0",
]
